## La Librería Numpy

Lo primero es importar la librería numpy

In [1]:
import numpy as np

## Creando Arrays

In [2]:
## ARRAY VACIO
A=np.empty([2,2])
print(A)
print('----------------------------------')
## ARRAY DE ZEROS
A=np.zeros([2,2])
print(A)
print('----------------------------------')
## ARRAY DE UNOS
A=np.ones([2,2])
print(A)
## ARRAY IDENTIDAD
A=np.identity(3)
print(A)
print('----------------------------------')
## ARRAY ALEATORIO
A=np.random.random([3,2])
print(A)
print('----------------------------------')
## ARRAY DE USANDO LINSPACE (ELIGIENDO EL NÚMERO DE VALORES)
A=np.linspace(1,10,10)
print(A)
print('----------------------------------')
## ARRAY USANDO ARANGE (SALTOS)
A=np.arange(1,10,0.5)
print(A)

[[4.64127994e-310 0.00000000e+000]
 [4.64237841e-310 4.64237807e-310]]
----------------------------------
[[0. 0.]
 [0. 0.]]
----------------------------------
[[1. 1.]
 [1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
----------------------------------
[[0.33942091 0.78089404]
 [0.65801633 0.0274594 ]
 [0.11000031 0.26021081]]
----------------------------------
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
----------------------------------
[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


## Características de un Array

In [3]:
## dimensiones
print(A.ndim)
## shape, numero de filas, columnas ...
print(A.shape)
## numero casillas
print(A.size)
## tipo de dato
print(A.dtype)

1
(18,)
18
float64


## Accediendo y modificando los elementos de un Array

<img src="https://iq.opengenus.org/content/images/2020/04/index.png"></img>

In [4]:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
A[2,0]=24
print(A)

[[ 1  2  3]
 [ 4  5  6]
 [24  8  9]]


In [6]:
A[:2,1:3]

array([[2, 3],
       [5, 6]])

## Filtrando Elementos de un Array

Recordar que se pueden combinar condiciones, & significa "and" o "intersección" y | signidica "or" o "unión"

In [7]:
A=np.array([[1,7,3,4],[2,12,4,1],[2,9,7,8]])
print(A)
A[(A%2==0) | (A%3==0)]

[[ 1  7  3  4]
 [ 2 12  4  1]
 [ 2  9  7  8]]


array([ 3,  4,  2, 12,  4,  2,  9,  8])

## Ejemplo:

1. Construir un array de 3 filas, donde:

    a. La primera fila este formada por 1,2,3,4.

    b. Los elementos de la segunda fila son el triple de los de la primera.

    c. Los elementos de la tercera fila son el cuadrado de de los de la segunda fila.


2. ¿Cuántos elementos del array son impares?

In [8]:
f1=[1,2,3,4]
M=np.array([f1,[3*k for k in f1],[(3*k)**2 for k in f1]])
print(M)
print('El número de elementos impares es: ',M[M%2!=0].size)

[[  1   2   3   4]
 [  3   6   9  12]
 [  9  36  81 144]]
El número de elementos impares es:  6


## ¿Qué son los axis (ejes) en un array?

<img src='https://predictivehacks.com/wp-content/uploads/2020/08/numpy_arrays-1024x572.png'></img>

In [9]:
A=np.array([7,2,9,10])
print(A)
print('--------------------')
B=np.array([[5.2,3.0,4.5],[9.1,0.1,0.3]])
print(B)

[ 7  2  9 10]
--------------------
[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


## Eliminar y añadir elementos

In [10]:
C=np.delete(A,1)
print(C)

[ 7  9 10]


In [11]:
D=np.delete(B,0,axis=1)
print(D)

[[3.  4.5]
 [0.1 0.3]]


In [12]:
E=np.append(B,[[6],[7]],axis=1)
print(E)

[[5.2 3.  4.5 6. ]
 [9.1 0.1 0.3 7. ]]


## Operaciones con Arrays
### Cambiando la forma de un array

In [13]:
A=np.linspace(1,36,36)
B=A.reshape(6,6)

### suma, resta, multiplicación y división

In [14]:
a=np.array([2,3,6])
b=np.array([4,7,9])
a+b
np.add(a,b)
a-b
np.subtract(a,b)
a*b
np.multiply(a,b)
a/b
np.divide(a,b)

array([0.5       , 0.42857143, 0.66666667])

### Operaciones matemáticas sobre los elementos de un array

In [31]:
M=np.array([1,2,3,4])
np.power(M,3)
np.log(M)
np.sqrt(M)
np.sin(M)
np.cos(M)
np.tan(M)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

### Operaciones estadísticas con arrays

In [32]:
r=np.random.random([5])
r

array([0.76612731, 0.15007529, 0.30609982, 0.95766819, 0.30372919])

In [37]:
np.mean(r)
np.median(r)
np.std(r)
np.max(r)
np.min(r)

0.15007529373303008

### Álgebra lineal con Arrays

In [68]:
a=np.array([1,2,3])
b=np.array([5,4,2])
c=np.array([2,5,6])
M=np.array([a,b,c])
np.transpose(M)

array([[1, 5, 2],
       [2, 4, 5],
       [3, 2, 6]])

Resolver el siguiente sistema lineal:

$$
\begin{aligned}
x+2y&=3\\
5x+4y&=4
\end{aligned}
$$

In [69]:
A=np.array([[1,2],[5,4]])
b=np.array([3,4])
np.linalg.solve(A,b)

array([-0.66666667,  1.83333333])